# Enable true color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g base-index 1
setw -g pane-base-index 1

# unbind C-b
# set -g prefix C-Space
# set-option -g prefix C-Space
# set-option -g prefix2 None

unbind %
bind | split-window -h -c "#{pane_current_path}" 

unbind '"'
bind-key \- split-window -v -c "#{pane_current_path}"

unbind v
bind v copy-mode

unbind r 
bind r source-file ~/.config/tmux/tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on
