[colors]
background = #000000
foreground = #FFFFFF
primary    = #3ddbd9
secondary  = #FFFFFF
; dim        = #f2f4f8

[bar/main]
inherit = bar/example
monitor = eDP-1
modules-left = bspwm
modules-center = date
modules-right = cava battery cpu memory volume

; [bar/sidebar]
; inherit = bar/example
; monitor = DP-1
; modules-left = bspwm
; modules-center = date
; modules-right = cava tray

[bar/example]
width = 80%
height = 25
radius = 6
offset-x = 10%
offset-y = 5
fixed-center = true


background = ${colors.background}
foreground = ${colors.foreground}

border-size = 1
; border-color = ${colors.dim}

padding-left = 2
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = Terminess Nerd Font:size=12;2
font-1 = FontAwesome:size=10;2
; font-1 = "Siji:size=20;3"


[global/wm]
margin-top = 0
margin-bottom = 0

[module/bspwm]
type = internal/bspwm
label-focused = %name%
label-focused-padding = 2
label-focused-background = ${colors.primary}
label-focused-foreground = ${colors.background}
label-occupied = %name%
label-occupied-padding = 2
label-occupied-foreground = ${colors.foreground}
label-empty = %name%
label-empty-padding = 2
label-empty-foreground = ${colors.dim}

[module/date]
type = internal/date
interval = 5
date = "%a %d %b"
time = "%H:%M"
label =  %time% %date%
label-foreground = ${colors.secondary}

[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/polybar/cava.sh
format = <label>
format-font = 5

[module/battery]
type = internal/battery
full-at = 100
low-at = 10
battery = BAT0
adapter = ADP0
poll-interval = 5
format-charging =  <label-charging>
label-charging- = %percentage%%
format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
format-full =  <label-full>
label-full = Full %percentage%%
format-low =  <label-low>
label-low = Low %percentage%%

label = %output%
[module/cpu]
type = internal/cpu
interval = 2
format =  <label>
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 3
format =  <label>
label = %percentage_used%%

[module/volume]
type = internal/pulseaudio
sink = alsa_output.pci-0000_00_1f.3.hdmi-stereo
format-volume = <label-volume>
label-volume =  %percentage%%
label-muted =  muted

[module/tray]
type = internal/tray
tray-background = ${colors.background}
tray-padding = 2
