#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
picom &
polybar main &
feh --bg-fill ~/Downloads/Pictures/Wallpapers/clay-banks-hwLAI5lRhdM-unsplash.jpg
bspc monitor -d '1' '2' '3' '4' '5'

bspc config border_width 0
bspc config window_gap 15
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a zen desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
